//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbAlumno
    {
        public string MatriculaTBAlum { get; set; }
        public string NombreTBAlum { get; set; }
        public string ApPaternoTBAlum { get; set; }
        public string ApMaternoTBAlum { get; set; }
        public string DireccionTBAlum { get; set; }
        public string TelefonoTBAlum { get; set; }
        public string EmailTBAlum { get; set; }
        public System.Guid ClienteIDTBAlum { get; set; }
        public bool EliminarTBAlum { get; set; }
        public int CarreraIDTBAlum { get; set; }
        public int SemestreTBAlum { get; set; }
        public string GrupoTBAlum { get; set; }
        public bool CuatriactTBAlum { get; set; }
    
        public virtual tbCarrera tbCarrera { get; set; }
        public virtual tbCliente tbCliente { get; set; }
    }
}
