//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCatalogo
    {
        public tbCatalogo()
        {
            this.tbRegistroes = new HashSet<tbRegistro>();
        }
    
        public System.Guid CatalogoIDTBCata { get; set; }
        public string DescripcionTBCata { get; set; }
    
        public virtual ICollection<tbRegistro> tbRegistroes { get; set; }
    }
}
