//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCarrera
    {
        public tbCarrera()
        {
            this.tbAlumnoes = new HashSet<tbAlumno>();
        }
    
        public string DescripcionTBCarr { get; set; }
        public bool EliminarTBCarr { get; set; }
        public int CarreraIDTBCarr { get; set; }
    
        public virtual ICollection<tbAlumno> tbAlumnoes { get; set; }
    }
}
