//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCliente
    {
        public tbCliente()
        {
            this.tbPrestamoes = new HashSet<tbPrestamo>();
        }
    
        public System.Guid ClienteIDTBClie { get; set; }
        public bool EliminarTBClie { get; set; }
        public bool TienePrestamoTBClie { get; set; }
    
        public virtual tbAlumno tbAlumno { get; set; }
        public virtual tbMaestro tbMaestro { get; set; }
        public virtual ICollection<tbPrestamo> tbPrestamoes { get; set; }
    }
}
