//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaterialPrestamo
    {
        public System.Guid PrestamoIDTBMaPr { get; set; }
        public System.Guid MaterialIDTBMaPr { get; set; }
        public int CantidadTBMaPr { get; set; }
        public Nullable<int> CantidadEntregadaTBMaPr { get; set; }
    
        public virtual tbMaterial tbMaterial { get; set; }
        public virtual tbPrestamo tbPrestamo { get; set; }
    }
}
