//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbMaterial
    {
        public tbMaterial()
        {
            this.tbMaterialPrestamoes = new HashSet<tbMaterialPrestamo>();
        }
    
        public System.Guid MaterialIDTBMate { get; set; }
        public string DescripcionTBMate { get; set; }
        public string MarcaTBMate { get; set; }
        public double CostoTBMate { get; set; }
        public int CantidadTBMate { get; set; }
        public bool EliminarTBMate { get; set; }
        public int EstadoTBMate { get; set; }
        public string CodigoTBMate { get; set; }
    
        public virtual tbEstado tbEstado { get; set; }
        public virtual ICollection<tbMaterialPrestamo> tbMaterialPrestamoes { get; set; }
    }
}
