//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNivel
    {
        public tbNivel()
        {
            this.tbUsuarios = new HashSet<tbUsuario>();
        }
    
        public int NivelIDTBNive { get; set; }
        public string DescripcionTBNive { get; set; }
    
        public virtual ICollection<tbUsuario> tbUsuarios { get; set; }
    }
}
