//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbPrestamo
    {
        public tbPrestamo()
        {
            this.tbMaterialPrestamoes = new HashSet<tbMaterialPrestamo>();
        }
    
        public System.Guid PrestamoIDTBPres { get; set; }
        public System.Guid UsuarioIDTBPres { get; set; }
        public System.Guid ClienteIDTBPres { get; set; }
        public System.DateTime FechaPrestamoTBPres { get; set; }
        public System.DateTime FechaEntregaTBPres { get; set; }
        public string ComentarioTBPres { get; set; }
        public Nullable<bool> ActivoTBPres { get; set; }
    
        public virtual tbCliente tbCliente { get; set; }
        public virtual ICollection<tbMaterialPrestamo> tbMaterialPrestamoes { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
