//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbRegistro
    {
        public int RegistroIDTBRegi { get; set; }
        public Nullable<System.TimeSpan> HoraTBRegi { get; set; }
        public Nullable<System.DateTime> FechaTBRegi { get; set; }
        public Nullable<System.Guid> CatalogoTBRegi { get; set; }
        public Nullable<System.Guid> UsuarioTBRegi { get; set; }
    
        public virtual tbCatalogo tbCatalogo { get; set; }
        public virtual tbUsuario tbUsuario { get; set; }
    }
}
