//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEB.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public tbUsuario()
        {
            this.tbPrestamoes = new HashSet<tbPrestamo>();
            this.tbRegistroes = new HashSet<tbRegistro>();
        }
    
        public System.Guid UsuarioIDTBUsua { get; set; }
        public string ContraseñaTBUsua { get; set; }
        public string NombreUsuarioTBUsua { get; set; }
        public string NombreTBUsua { get; set; }
        public string ApPaternoTBUsua { get; set; }
        public string ApMaternoTBUsua { get; set; }
        public bool EliminarTBUsua { get; set; }
        public int UsuarioTipoTBUsua { get; set; }
        public Nullable<int> NivelTBUsua { get; set; }
    
        public virtual tbNivel tbNivel { get; set; }
        public virtual ICollection<tbPrestamo> tbPrestamoes { get; set; }
        public virtual tbTipoUsuario tbTipoUsuario { get; set; }
        public virtual ICollection<tbRegistro> tbRegistroes { get; set; }
    }
}
